let variable = [
  {
    _id: { $oid: "61f50bb469540b32a366059c" },
    board: [{ $oid: "61f3b6116992fe58b6805980" }],
    syllabus: [{ $oid: "61f3b6596992fe58b6805a33" }],
    chapter: [{ $oid: "61f50a0369540b32a366048d" }],
    topic: [],
    learningOutcome: [],
    questionCategory: null,
    examType: [],
    questionType: ["mcq"],
    practiceAndTestQuestion: [],
    studentType: [],
    difficultyLevel: "intermediate",
    question: [
      '<p>if&nbsp;<span id="MathJax-Element-1-Frame" class="mjx-chtml MathJax_CHTML" style="box-sizing: border-box; border: 0px; font-size: 16.95px; font-style: normal; font-weight: 400; margin: 0px; outline: 0px; padding: 1px 0px; vertical-align: baseline; display: inline-block; line-height: 0; text-indent: 0px; text-align: left; text-transform: none; letter-spacing: normal; overflow-wrap: normal; word-spacing: 0px; white-space: nowrap; float: none; direction: ltr; max-width: none; max-height: none; min-width: 0px; min-height: 0px; color: #3A3A3A; font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Oxygen-Sans, Ubuntu, Cantarell, \'Helvetica Neue\', sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; background-color: #FFFFFF; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; position: relative;" tabindex="0" role="presentation" data-mathml="&lt;math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;mi&gt;f&lt;/mi&gt;&lt;mo stretchy=&quot;false&quot;&gt;(&lt;/mo&gt;&lt;mi&gt;x&lt;/mi&gt;&lt;mo stretchy=&quot;false&quot;&gt;)&lt;/mo&gt;&lt;mo&gt;+&lt;/mo&gt;&lt;mn&gt;2&lt;/mn&gt;&lt;mi&gt;f&lt;/mi&gt;&lt;mo stretchy=&quot;false&quot;&gt;(&lt;/mo&gt;&lt;mn&gt;1&lt;/mn&gt;&lt;mo&gt;&amp;#x2212;&lt;/mo&gt;&lt;mi&gt;x&lt;/mi&gt;&lt;mo stretchy=&quot;false&quot;&gt;)&lt;/mo&gt;&lt;mo&gt;=&lt;/mo&gt;&lt;msup&gt;&lt;mi&gt;x&lt;/mi&gt;&lt;mn&gt;2&lt;/mn&gt;&lt;/msup&gt;&lt;mo&gt;+&lt;/mo&gt;&lt;mn&gt;2&lt;/mn&gt;&lt;/math&gt;"><span id="MJXc-Node-1" class="mjx-math" aria-hidden="true"><span id="MJXc-Node-2" class="mjx-mrow"><span id="MJXc-Node-3" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I">f</span></span><span id="MJXc-Node-4" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R">(</span></span><span id="MJXc-Node-5" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I">x</span></span><span id="MJXc-Node-6" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R">)</span></span><span id="MJXc-Node-7" class="mjx-mo MJXc-space2"><span class="mjx-char MJXc-TeX-main-R">+</span></span><span id="MJXc-Node-8" class="mjx-mn MJXc-space2"><span class="mjx-char MJXc-TeX-main-R">2</span></span><span id="MJXc-Node-9" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I">f</span></span><span id="MJXc-Node-10" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R">(</span></span><span id="MJXc-Node-11" class="mjx-mn"><span class="mjx-char MJXc-TeX-main-R">1</span></span><span id="MJXc-Node-12" class="mjx-mo MJXc-space2"><span class="mjx-char MJXc-TeX-main-R">&minus;</span></span><span id="MJXc-Node-13" class="mjx-mi MJXc-space2"><span class="mjx-char MJXc-TeX-math-I">x</span></span><span id="MJXc-Node-14" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R">)</span></span><span id="MJXc-Node-15" class="mjx-mo MJXc-space3"><span class="mjx-char MJXc-TeX-main-R">=</span></span><span id="MJXc-Node-16" class="mjx-msubsup MJXc-space3"><span class="mjx-base"><span id="MJXc-Node-17" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I">x</span></span></span><span class="mjx-sup"><span id="MJXc-Node-18" class="mjx-mn"><span class="mjx-char MJXc-TeX-main-R">2</span></span></span></span><span id="MJXc-Node-19" class="mjx-mo MJXc-space2"><span class="mjx-char MJXc-TeX-main-R">+</span></span><span id="MJXc-Node-20" class="mjx-mn MJXc-space2"><span class="mjx-char MJXc-TeX-main-R">2</span></span></span></span><span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><mi>f</mi><mo stretchy="false">(</mo><mi>x</mi><mo stretchy="false">)</mo><mo>+</mo><mn>2</mn><mi>f</mi><mo stretchy="false">(</mo><mn>1</mn><mo>&minus;</mo><mi>x</mi><mo stretchy="false">)</mo><mo>=</mo><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><mn>2</mn></math></span></span>&nbsp;,&nbsp;<span id="MathJax-Element-2-Frame" class="mjx-chtml MathJax_CHTML" style="box-sizing: border-box; border: 0px; font-size: 16.95px; font-style: normal; font-weight: 400; margin: 0px; outline: 0px; padding: 1px 0px; vertical-align: baseline; display: inline-block; line-height: 0; text-indent: 0px; text-align: left; text-transform: none; letter-spacing: normal; overflow-wrap: normal; word-spacing: 0px; white-space: nowrap; float: none; direction: ltr; max-width: none; max-height: none; min-width: 0px; min-height: 0px; color: #3A3A3A; font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Oxygen-Sans, Ubuntu, Cantarell, \'Helvetica Neue\', sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; background-color: #FFFFFF; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; position: relative;" tabindex="0" role="presentation" data-mathml="&lt;math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;mi&gt;x&lt;/mi&gt;&lt;mo&gt;&amp;#x2208;&lt;/mo&gt;&lt;mi&gt;R&lt;/mi&gt;&lt;/math&gt;"><span id="MJXc-Node-21" class="mjx-math" aria-hidden="true"><span id="MJXc-Node-22" class="mjx-mrow"><span id="MJXc-Node-23" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I">x</span></span><span id="MJXc-Node-24" class="mjx-mo MJXc-space3"><span class="mjx-char MJXc-TeX-main-R">&isin;</span></span><span id="MJXc-Node-25" class="mjx-mi MJXc-space3"><span class="mjx-char MJXc-TeX-math-I">R</span></span></span></span><span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><mi>x</mi><mo>&isin;</mo><mi>R</mi></math></span></span>, then f(x) is given by</p>',
    ],
    questions: [],
    options: [
      { value: "<p>f(x)=(x&minus;2)23</p>", file_text: "" },
      { value: "<p>f(x)=1</p>", file_text: "" },
      { value: "<p>f(x)=x−2</p>", file_text: "" },
      { value: "<p>f(x)=x2−2</p>", file_text: "" },
    ],
    answer: [{ value: "<p>f(x)=(x&minus;2)23</p>", file_text: "" }],
    totalMarks: 5,
    negativeMarks: 0,
    repository: [{ id: "61f3b9056992fe58b6805c75", repository_type: "School" }],
    attempt_count: 0,
    wrong_count: 0,
    createdAt: { $date: "2022-01-29T04:19:48.891Z" },
    updatedAt: { $date: "2022-01-29T04:19:48.891Z" },
    class: { $oid: "61f4ca2469540b32a365f51e" },
    subject: { $oid: "61f3b6496992fe58b68059d8" },
    language: "English",
    questionTitle: "1",
    optionsType: "text",
    matchOptions: { column1: [], column2: [], column3: [] },
    reason: null,
    negativeScore: "NO",
    duration: "5",
    createdBy: "admin",
    question_count: 1000,
    __v: 0,
  },
  {
    _id: { $oid: "61f50e2769540b32a36606f4" },
    board: [{ $oid: "61f3b6116992fe58b6805980" }],
    syllabus: [{ $oid: "61f3b6596992fe58b6805a33" }],
    chapter: [{ $oid: "61f50a0369540b32a366048d" }],
    topic: [],
    learningOutcome: [],
    questionCategory: null,
    examType: [],
    questionType: ["objectives"],
    practiceAndTestQuestion: [],
    studentType: [],
    difficultyLevel: "intermediate",
    question: [
      "<p>The function f : R&nbsp;&rarr; R defined by f (x) = (x &ndash; 1) (x &ndash; 2) (x &ndash; 3) is</p>",
    ],
    questions: [],
    options: [
      { value: "<p>both one-one and onto</p>", file_text: "" },
      { value: "<p>onto but not one-one</p>", file_text: "" },
      { value: "<p>neither one-one nor onto</p>", file_text: "" },
      { value: "<p>one-one but not onto</p>", file_text: "" },
    ],
    answer: [{ value: "<p>both one-one and onto</p>", file_text: "" }],
    totalMarks: 5,
    negativeMarks: 0,
    repository: [{ id: "61f3b9056992fe58b6805c75", repository_type: "School" }],
    attempt_count: 0,
    wrong_count: 0,
    createdAt: { $date: "2022-01-29T04:19:48.891Z" },
    updatedAt: { $date: "2022-01-29T04:19:48.891Z" },
    class: { $oid: "61f4ca2469540b32a365f51e" },
    subject: { $oid: "61f3b6496992fe58b68059d8" },
    language: "English",
    questionTitle: "2",
    optionsType: "text",
    matchOptions: { column1: [], column2: [], column3: [] },
    reason: null,
    negativeScore: "NO",
    duration: "5",
    createdBy: "admin",
    question_count: 1001,
    __v: 0,
  },
  {
    _id: { $oid: "61f50ff669540b32a366082d" },
    board: [{ $oid: "61f3b6116992fe58b6805980" }],
    syllabus: [{ $oid: "61f3b6596992fe58b6805a33" }],
    chapter: [{ $oid: "61f50a0369540b32a366048d" }],
    topic: [],
    learningOutcome: [],
    questionCategory: null,
    examType: [],
    questionType: ["twoColMtf"],
    practiceAndTestQuestion: [],
    studentType: [],
    difficultyLevel: "intermediate",
    question: [
      '<table style="height: 27.3906px;" border="0" width="100%" cellspacing="0" cellpadding="0">\n<tbody>\n<tr style="height: 27.3906px;">\n<td style="height: 27.3906px;" valign="top">\n<p>Match the following:</p>\n</td>\n</tr>\n</tbody>\n</table>',
    ],
    questions: [],
    options: [
      { value: "A-4, B-3, C-1, D-2" },
      { value: "A-3, B-4, C-2, D-1" },
      { value: "A-3, B-4, C-1, D-2" },
      { value: "A-4, B-3, C-2, D-1" },
    ],
    answer: [{ value: "A-4, B-3, C-1, D-2" }],
    totalMarks: 5,
    negativeMarks: 0,
    repository: [{ id: "61f3b9056992fe58b6805c75", repository_type: "School" }],
    attempt_count: 0,
    wrong_count: 0,
    createdAt: { $date: "2022-01-29T04:19:48.891Z" },
    updatedAt: { $date: "2022-01-29T04:19:48.891Z" },
    class: { $oid: "61f4ca2469540b32a365f51e" },
    subject: { $oid: "61f3b6496992fe58b68059d8" },
    language: "English",
    questionTitle: "4",
    optionsType: "text",
    matchOptions: {
      column1: [
        { type: 1, value: "<p>RC coupled amplifier</p>", file_text: "" },
        { type: 2, value: "<p>Tuned amplifier</p>", file_text: "" },
        {
          type: 3,
          value: "<p>Chopper stabilized amplifier</p>",
          file_text: "",
        },
        { type: 4, value: "<p>DC amplifier</p>", file_text: "" },
      ],
      column2: [
        {
          type: "A",
          value: "<p>Peak in gain frequency response</p>",
          file_text: "",
        },
        {
          type: "B",
          value:
            "<p>Flat frequency response with upper and lower cut off frequency</p>",
          file_text: "",
        },
        {
          type: "C",
          value: "<p>Flat frequency response from zero frequency onwards</p>",
          file_text: "",
        },
        { type: "D", value: "<p>Very low drift</p>", file_text: "" },
      ],
      column3: [],
    },
    reason: null,
    negativeScore: "NO",
    duration: "5",
    createdBy: "admin",
    question_count: 1002,
    __v: 0,
  },
];

function abc(object) {
  let a = [];
  for (let i of variable) {
    if (i.difficultyLevel == object) {
      a.push(i.questionType);
    }
  }
  return a;
}
console.log(abc("intermediate"));
